version: '2.1'
services:
  ckan:
    container_name: ckan
    image: geosolutionsit/ckan:${CKAN_IMAGE_TAG}
    volumes:
      - "./ckan.ini:/etc/ckan/ckan.ini"
    ports:
        - "5000:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    depends_on:
      - db
      - solr
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m
      timeout: 5s
      retries: 3

  solr:
    container_name: solr
    image: solr:7
    #ports:
    #    - "8983:8983"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983"]
      interval: 1m
      timeout: 5s
      retries: 3

  db:
    container_name: db
    image: ckan/postgresql:latest
    #ports:
    #    - "5432:5432"
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-U", "postgres", "-c", "SELECT 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      
  redis:
    container_name: redis
    image: redis:latest
    #ports:
    #    - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379" , "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
